/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Logins;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hp
 */
public class Travelling_Management_System extends javax.swing.JFrame {

    
    double diu;
    
    cFlight cost = new cFlight();
    /** Creates new form Travelling_Management_System */
    
    public Travelling_Management_System() {
       super("Travelling_Management_System");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtnTotal = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnReceipt = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jlblSubtotal = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jrbReturn = new javax.swing.JRadioButton();
        jrbStandard1 = new javax.swing.JRadioButton();
        jrbSingle = new javax.swing.JRadioButton();
        jcbSpecialneeds = new javax.swing.JCheckBox();
        jlblStandard = new javax.swing.JLabel();
        jlblEconomy = new javax.swing.JLabel();
        jlblFirstClass = new javax.swing.JLabel();
        jlblSingle = new javax.swing.JLabel();
        jlblReturn = new javax.swing.JLabel();
        jrbEconomy = new javax.swing.JRadioButton();
        jrbFirstClass = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtLastname = new javax.swing.JTextField();
        jtxtPhonenumber = new javax.swing.JTextField();
        jtxtAdress = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jcbAmo2 = new javax.swing.JCheckBox();
        jcbAirporttax = new javax.swing.JCheckBox();
        jcbTravellingInsurance = new javax.swing.JCheckBox();
        jcbExtluggage = new javax.swing.JCheckBox();
        jcmbAccommodation = new javax.swing.JComboBox<>();
        jcmbDeparture = new javax.swing.JComboBox<>();
        jcmbDestinationa = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(51, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Travel Managment System");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 4));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 950, 90));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1280, 110));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnExit.setBackground(new java.awt.Color(255, 51, 51));
        jbtnExit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(0, 51, 0));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 80, -1));

        jbtnTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, -1));

        jbtnReset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 80, -1));

        jbtnReceipt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnReceipt.setText("Receipt");
        jbtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceiptActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jbtnPrint.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 90, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, 620, 80));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Total");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Subtotal");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Tax");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 30));

        jlblTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblTotal.setText("0");
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel5.add(jlblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 120, 30));

        jlblTax.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblTax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblTax.setText("0");
        jlblTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel5.add(jlblTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 120, 30));

        jlblSubtotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblSubtotal.setText("0");
        jlblSubtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel5.add(jlblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 120, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 320, 160));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrbReturn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jrbReturn.setText("Return");
        jrbReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbReturnActionPerformed(evt);
            }
        });
        jPanel6.add(jrbReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jrbStandard1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jrbStandard1.setText("Standard");
        jrbStandard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbStandard1ActionPerformed(evt);
            }
        });
        jPanel6.add(jrbStandard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jrbSingle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jrbSingle.setText("Single");
        jrbSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSingleActionPerformed(evt);
            }
        });
        jPanel6.add(jrbSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jcbSpecialneeds.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jcbSpecialneeds.setText("Special Needs");
        jcbSpecialneeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSpecialneedsActionPerformed(evt);
            }
        });
        jPanel6.add(jcbSpecialneeds, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jlblStandard.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblStandard.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblStandard.setText("0");
        jlblStandard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel6.add(jlblStandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 120, 30));

        jlblEconomy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblEconomy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblEconomy.setText("0");
        jlblEconomy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel6.add(jlblEconomy, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, 30));

        jlblFirstClass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblFirstClass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblFirstClass.setText("0");
        jlblFirstClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel6.add(jlblFirstClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 120, 30));

        jlblSingle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblSingle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblSingle.setText("0");
        jlblSingle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel6.add(jlblSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 120, 30));

        jlblReturn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblReturn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblReturn.setText("0");
        jlblReturn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel6.add(jlblReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 120, 30));

        jrbEconomy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jrbEconomy.setText("Economy");
        jrbEconomy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEconomyActionPerformed(evt);
            }
        });
        jPanel6.add(jrbEconomy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 101, -1, 30));

        jrbFirstClass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jrbFirstClass.setText("First Class");
        jrbFirstClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFirstClassActionPerformed(evt);
            }
        });
        jPanel6.add(jrbFirstClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 650, 250));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Email");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 100, 30));

        jtxtFirstname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel7.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, 30));

        jtxtLastname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel7.add(jtxtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 220, 30));

        jtxtPhonenumber.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel7.add(jtxtPhonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 220, 30));

        jtxtAdress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel7.add(jtxtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 220, 30));

        jtxtEmail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel7.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 220, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Firstname");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Lastname");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Adress");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Phone number");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, 30));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 500, 320));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Accommodation");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Destination");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Departure");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        jcbAmo2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jcbAmo2.setText("Air Miles Over 20000");
        jcbAmo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAmo2ActionPerformed(evt);
            }
        });
        jPanel8.add(jcbAmo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jcbAirporttax.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jcbAirporttax.setText("Airport Tax");
        jcbAirporttax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAirporttaxActionPerformed(evt);
            }
        });
        jPanel8.add(jcbAirporttax, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jcbTravellingInsurance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jcbTravellingInsurance.setText("Travelling Insurance ");
        jcbTravellingInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTravellingInsuranceActionPerformed(evt);
            }
        });
        jPanel8.add(jcbTravellingInsurance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jcbExtluggage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jcbExtluggage.setText("Ext Luggage");
        jcbExtluggage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbExtluggageActionPerformed(evt);
            }
        });
        jPanel8.add(jcbExtluggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jcmbAccommodation.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jcmbAccommodation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Single", "Double", "Extra" }));
        jPanel8.add(jcmbAccommodation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 280, -1));

        jcmbDeparture.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jcmbDeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Heathrow Airport", "Gatwick  Airport", "DFW  Airport", "Oslo  Airport", "Nairobi  Airport", "MM Airport", "Santa Maria  Airport", "Beijing International Airport", "Shahjalal International Airport" }));
        jPanel8.add(jcmbDeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 280, -1));

        jcmbDestinationa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jcmbDestinationa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bangladesh - 5 days in Cox's Bazar", "Canada - 7 days in Tornto", "Canada - 7 days in Ottawn", "Norway - 7 days in Oslo", "Nigeria- 5 days in Lagos EKO Atlantin", "India- 5 days in Lagos New Delhi", "Italy- 5 days in Rome", "USA- 5 days in Dallas Forth worth", "USA- 5 days in Alaska", "UK- 5 days in London", "UK- 5 days in Wales", "France- 5 days in Paris", "Keneya- 5 days in Nairobi", "Ghana- 5 days in Accra", "South Africa - 4 days in Cape Town", "Brazil- 4 days in Sao Poulo", "Jamaican- 4  days in Kingston", "Phlippines- 5 days in Marila", "Ireland - 4 days in Dublin" }));
        jcmbDestinationa.setEnabled(false);
        jcmbDestinationa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbDestinationaActionPerformed(evt);
            }
        });
        jPanel8.add(jcmbDestinationa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 280, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 460, 320));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 280, 420));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("   Receipt");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 4));
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 100, 30));
        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 60, 60));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 140, 300, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbAmo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAmo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAmo2ActionPerformed

    private void jcbAirporttaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAirporttaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAirporttaxActionPerformed

    private void jcbTravellingInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTravellingInsuranceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTravellingInsuranceActionPerformed

    private void jcbExtluggageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbExtluggageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbExtluggageActionPerformed

    private void jcbSpecialneedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSpecialneedsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSpecialneedsActionPerformed

    private void jrbSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbSingleActionPerformed

    private void jrbReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbReturnActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
     cQuit cExit = new cQuit();
     cExit.quit();
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
       
       cCostTax iTax = new cCostTax();
       double iTaxes,subtotal,total;
       if(jrbStandard1.isSelected())
       {
           subtotal = diu ;
           String isubtotal = String.format("$%.2f",subtotal);
           jlblSubtotal.setText(isubtotal);
           iTaxes = iTax.cFIndTax(subtotal);
           String Tax = String.format("$%.2f",iTaxes);
           jlblTax.setText(Tax);
           String iTotal = String.format("$%.2f",subtotal+iTaxes);
           jlblTotal.setText(iTotal);
           jlblStandard.setText(isubtotal);
            
       }
       else if(jrbEconomy.isSelected())
       {
           
           subtotal = diu +75 ;
           String isubtotal = String.format("$%.2f",subtotal);
           jlblSubtotal.setText(isubtotal);
           iTaxes = iTax.cFIndTax(subtotal);
           String Tax = String.format("$%.2f",iTaxes);
           jlblTax.setText(Tax);
           String iTotal = String.format("$%.2f",subtotal+iTaxes);
           jlblTotal.setText(iTotal);
            jlblEconomy.setText(isubtotal);
       }
        else if(jrbFirstClass.isSelected())
       {
           
           subtotal = diu +150;
           String isubtotal = String.format("$%.2f",subtotal);
           jlblSubtotal.setText(isubtotal);
           iTaxes = iTax.cFIndTax(subtotal);
           String Tax = String.format("$%.2f",iTaxes);
           jlblTax.setText(Tax);
           String iTotal = String.format("$%.2f",subtotal+iTaxes);
           jlblTotal.setText(iTotal);
           jlblFirstClass.setText(isubtotal);
           
       }
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jcmbDestinationaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbDestinationaActionPerformed

        
       if ((jcmbDestinationa.getSelectedItem().equals("Bangladesh - 5 days in Cox's Bazar"))&& jrbStandard1.isSelected())
       {
           diu = cost.Bangladesh;
           String Cost = String.format("$%.2f", diu);
           jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
       else  if ((jcmbDestinationa.getSelectedItem().equals("Canada - 7 days in Tornto"))&& jrbStandard1.isSelected())
       {
            diu = cost.Canada_T;
          String Cost = String.format("$%.2f", diu);
           jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
       else  if ((jcmbDestinationa.getSelectedItem().equals("Canada - 7 days in Ottawn"))&& jrbStandard1.isSelected())
       {
         diu = cost.Canada_O;
          String Cost = String.format("$%.2f",diu);
           jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
       else  if ((jcmbDestinationa.getSelectedItem().equals("Norway - 7 days in Oslo"))&& jrbStandard1.isSelected())
       {
                       diu = cost.Norway;
          String Cost = String.format("$%.2f", diu);
           jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
       else  if ((jcmbDestinationa.getSelectedItem().equals("Nigeria- 5 days in Lagos EKO Atlantin"))&& jrbStandard1.isSelected())
       {
                       diu = cost.Nigeria;
          String Cost = String.format("$%.2f", diu);
           jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
       else  if ((jcmbDestinationa.getSelectedItem().equals("India- 5 days in Lagos New Delhi"))&& jrbStandard1.isSelected())
       {
                       diu = cost.India;
          String Cost = String.format("$%.2f", diu);
           jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
       else  if ((jcmbDestinationa.getSelectedItem().equals("Italy- 5 days in Rome"))&& jrbStandard1.isSelected())
       {
                       diu = cost.Italy;
          String Cost = String.format("$%.2f", cost.Italy);
           jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
        
        //==============================================================================================
        
        else if ((jcmbDestinationa.getSelectedItem().equals("Bangladesh - 5 days in Cox's Bazar"))&& jrbEconomy.isSelected())
       {
                       diu = cost.Bangladesh;
          String Cost = String.format("$%.2f", diu + 75);
           jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
           
            
       }
        else  if ((jcmbDestinationa.getSelectedItem().equals("Canada - 7 days in Tornto"))&& jrbEconomy.isSelected())
       {
                       diu = cost.Canada_T;
          String Cost = String.format("$%.2f", diu + 75);
           jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
        else if ((jcmbDestinationa.getSelectedItem().equals("Canada - 7 days in Ottawn"))&& jrbEconomy.isSelected())
       {
                       diu = cost.Canada_O;
          String Cost = String.format("$%.2f", diu + 75);
           jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
        else if ((jcmbDestinationa.getSelectedItem().equals("Norway - 7 days in Oslo"))&& jrbEconomy.isSelected())
       {
                       diu = cost.Norway;
          String Cost = String.format("$%.2f", diu + 75);
           jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
        else  if ((jcmbDestinationa.getSelectedItem().equals("Nigeria- 5 days in Lagos EKO Atlantin"))&& jrbEconomy.isSelected())
       {
                       diu = cost.Nigeria;
          String Cost = String.format("$%.2f", diu + 75);
           jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
        else if ((jcmbDestinationa.getSelectedItem().equals("India- 5 days in Lagos New Delhi"))&& jrbEconomy.isSelected())
       {
                       diu = cost.India;
          String Cost = String.format("$%.2f", diu + 75);
           jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
         

        else if ((jcmbDestinationa.getSelectedItem().equals("Italy- 5 days in Rome"))&& jrbEconomy.isSelected())
       {
                       diu = cost.Italy;
          String Cost = String.format("$%.2f", diu + 75);
           jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
            
       }
       //=========================================================================================================
        else if ((jcmbDestinationa.getSelectedItem().equals("Bangladesh - 5 days in Cox's Bazar"))&& jrbFirstClass.isSelected())
       {
                       diu = cost.Bangladesh;
          String Cost = String.format("$%.2f", cost.Bangladesh + 150);
           jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
        else  if ((jcmbDestinationa.getSelectedItem().equals("Canada - 7 days in Tornto"))&& jrbFirstClass.isSelected())
       {
                       diu = cost.Canada_T;
          String Cost = String.format("$%.2f", diu + 150);
           jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
        else  if ((jcmbDestinationa.getSelectedItem().equals("Canada - 7 days in Ottawn"))&& jrbFirstClass.isSelected())
       {
                       diu = cost.Canada_O;
          String Cost = String.format("$%.2f", diu + 150);
           jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
        else if ((jcmbDestinationa.getSelectedItem().equals("Norway - 7 days in Oslo"))&& jrbFirstClass.isSelected())
       {
                       diu = cost.Norway;
          String Cost = String.format("$%.2f", diu + 150);
           jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
        else  if ((jcmbDestinationa.getSelectedItem().equals("Nigeria- 5 days in Lagos EKO Atlantin"))&& jrbFirstClass.isSelected())
       {
                       diu = cost.Nigeria;
          String Cost = String.format("$%.2f", diu + 150);
           jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
        else  if ((jcmbDestinationa.getSelectedItem().equals("India- 5 days in Lagos New Delhi"))&& jrbFirstClass.isSelected())
       {
                       diu = cost.India;
          String Cost = String.format("$%.2f", diu + 150);
           jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
         

        else if ((jcmbDestinationa.getSelectedItem().equals("Italy- 5 days in Rome"))&& jrbFirstClass.isSelected())
       {
                       diu = cost.Italy;
          String Cost = String.format("$%.2f", diu + 150);
           jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
       }
        
    }//GEN-LAST:event_jcmbDestinationaActionPerformed

    private void jrbStandard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbStandard1ActionPerformed
        
        if (jrbStandard1.isSelected() == true)
        {
            jcmbDestinationa.setEnabled(true);
            jcmbDestinationa.setSelectedItem("None");
            jrbEconomy.setSelected(false);
            jrbFirstClass.setSelected(false);
            jlblEconomy.setText("0");
            jlblFirstClass.setText("0");
            jlblSingle.setText("0");
            jlblReturn.setText("0");
            
        }
        else if (jrbStandard1.isSelected() == false)
        {
            jcmbDestinationa.setSelectedItem("None");
            jcmbDestinationa.setEnabled(false);
            jlblStandard.setText("0");
        }
    }//GEN-LAST:event_jrbStandard1ActionPerformed

    private void jrbEconomyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEconomyActionPerformed
         
        if (jrbEconomy.isSelected() == true)
        {
            jcmbDestinationa.setEnabled(true);
            jcmbDestinationa.setSelectedItem("None");
            jrbStandard1.setSelected(false);
            jrbFirstClass.setSelected(false);
            jlblStandard.setText("0");
            jlblFirstClass.setText("0");
            jlblSingle.setText("0");
            jlblReturn.setText("0");
            
        }
        else if (jrbEconomy.isSelected() == false)
        {
            jcmbDestinationa.setSelectedItem("None");
            jcmbDestinationa.setEnabled(false);
            jlblEconomy.setText("0");
        }
    }//GEN-LAST:event_jrbEconomyActionPerformed

    private void jrbFirstClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFirstClassActionPerformed
        if (jrbFirstClass.isSelected() == true)
        {
            jcmbDestinationa.setEnabled(true);
            jcmbDestinationa.setSelectedItem("None");
            jrbStandard1.setSelected(false);
            jrbEconomy.setSelected(false);
            jlblStandard.setText("0");
            jlblEconomy.setText("0");
            jlblSingle.setText("0");
            jlblReturn.setText("0");
            
        }
        else if (jrbFirstClass.isSelected() == false)
        {
            jcmbDestinationa.setSelectedItem("None");
            jcmbDestinationa.setEnabled(false);
            jlblFirstClass.setText("0");
        }
    }//GEN-LAST:event_jrbFirstClassActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        
       jtxtFirstname.setText(null);
       jtxtLastname.setText(null);
       jtxtAdress.setText(null);
       jtxtPhonenumber.setText(null);
       jtxtEmail.setText(null);
       jcmbDeparture.setSelectedItem("None");
       jcmbDestinationa.setSelectedItem("None");
       jcmbAccommodation.setSelectedItem("None");
       jlblStandard.setText(null);
       jlblEconomy.setText(null);
       jlblFirstClass.setText(null);
       jlblSingle.setText(null);
       jlblReturn.setText(null);
       jlblTax.setText(null);
       jlblSubtotal.setText(null);
       jlblTotal.setText(null);
       jcbAirporttax.setSelected(false);
       jcbAmo2.setSelected(false);
       jcbTravellingInsurance.setSelected(false);
       jcbExtluggage.setSelected(false);
       jcbSpecialneeds.setSelected(false);
       jtxtReceipt.setText(null);
       jrbStandard1.setSelected(false);
        jrbEconomy.setSelected(false);
         jrbFirstClass.setSelected(false);
          jrbSingle.setSelected(false);
       
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceiptActionPerformed
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new  SimpleDateFormat("HH:mm:ss");
        String iTime=(tTime.format(timer.getTime()));
         SimpleDateFormat Tdate = new  SimpleDateFormat("dd-MMM-YYYY");
        String iDate=(Tdate.format(timer.getTime()));
        
        int num1;
        String ref= "" ;
        num1= 1325 + (int)(Math.random()*4238);
         ref+=num1+1325;
         
         
         //===============================
         String Firstname=(jtxtFirstname.getText());
         String Lastname=(jtxtLastname.getText());
         String Adress=(jtxtAdress.getText());
         String Phonenumber=(jtxtPhonenumber.getText());
         String Email=(jtxtEmail.getText());
         String Tax=(jlblTax.getText());
         String Subtotal=(jlblSubtotal.getText());
         String Total=(jlblTotal.getText());
         
         jtxtReceipt.append("Travel Management System:\n\n"
                 +"Ref\t:" +ref
                 +"\n*******************"
                 +"\nFirstName\t:"+Firstname
                 +"\nLastName\t:"+Lastname
                 +"\nAdress\t:"+Adress
                 +"\nPhonenumber\t:"+Phonenumber
                 +"\nEmail\t:"+Email
                 +"\nTax\t:"+Tax
                 +"\nSubtotal\t:"+Subtotal
                 +"\nTotal\t:"+Total
                 +"\n *******************************************"
                 +"\n\nDate:" + iDate +"\tTime:"+iTime
                 +"\n\n Thanks for Using \nTravel Management System"
                 +"\n=========================="
                 +"\n Developed By Mahabub Alam Shawon");
         
    }//GEN-LAST:event_jbtnReceiptActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        try {
            jtxtReceipt.print();
                    } catch (PrinterException ex) {
            Logger.getLogger(Travelling_Management_System.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Image a=Toolkit.getDefaultToolkit().createImage("travellogo.jpg");
    }//GEN-LAST:event_formMouseClicked
 
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Travelling_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Travelling_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Travelling_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Travelling_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Travelling_Management_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JCheckBox jcbAirporttax;
    private javax.swing.JCheckBox jcbAmo2;
    private javax.swing.JCheckBox jcbExtluggage;
    private javax.swing.JCheckBox jcbSpecialneeds;
    private javax.swing.JCheckBox jcbTravellingInsurance;
    private javax.swing.JComboBox<String> jcmbAccommodation;
    private javax.swing.JComboBox<String> jcmbDeparture;
    private javax.swing.JComboBox<String> jcmbDestinationa;
    private javax.swing.JLabel jlblEconomy;
    private javax.swing.JLabel jlblFirstClass;
    private javax.swing.JLabel jlblReturn;
    private javax.swing.JLabel jlblSingle;
    private javax.swing.JLabel jlblStandard;
    private javax.swing.JLabel jlblSubtotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JRadioButton jrbEconomy;
    private javax.swing.JRadioButton jrbFirstClass;
    private javax.swing.JRadioButton jrbReturn;
    private javax.swing.JRadioButton jrbSingle;
    private javax.swing.JRadioButton jrbStandard1;
    private javax.swing.JTextField jtxtAdress;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtLastname;
    private javax.swing.JTextField jtxtPhonenumber;
    private javax.swing.JTextArea jtxtReceipt;
    // End of variables declaration//GEN-END:variables

}
